#include "web_content.h"

// Login HTML
const char* get_login_html(void) {
    return "<!DOCTYPE html><html lang=\"es\"><head><meta charset=\"UTF-8\" /><title>Login - ESP32 Terminal</title>"
           "<link rel=\"stylesheet\" href=\"/login.css\"></head><body> "
           "<div class=\"box\"> "
           "<div class=\"smiley\"> "
           "<svg viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" fill=\"none\" stroke=\"#33ff33\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"> "
           "<circle cx=\"32\" cy=\"32\" r=\"30\"/> "
           "<circle cx=\"22\" cy=\"24\" r=\"4\"/> "
           "<circle cx=\"42\" cy=\"24\" r=\"4\"/> "
           "<path d=\"M 20 42 Q 32 50 44 42\"/> "
           "</svg> "
           "</div> "
           "<div class=\"title\">ESP32 Terminal</div> "
           "<form id=\"loginForm\"> "
           "<input class=\"input-field\" name=\"user\" placeholder=\"usuario\" value=\"root\" required /><br/> "
           "<input class=\"input-field\" name=\"pass\" type=\"password\" placeholder=\"contraseña\" required /><br/> "
           "<button class=\"btn\" type=\"submit\">Entrar</button> "
           "</form> "
           "<div id=\"error\" class=\"error\"></div> "
           "<div class=\"small\">Inactividad 3 min = logout</div> "
           "</div>"
           "<script src=\"/login.js\"></script></body></html>";
}

// Login CSS
const char* get_login_css(void) {
    return "body { background: black; color: #33ff33; font-family: monospace; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin:0; } "
           ".box { border: 2px solid #33ff33; padding: 20px 30px; border-radius: 8px; width: 320px; text-align: center; position: relative; } "
           ".title { font-size: 1.3em; font-weight: bold; margin-bottom: 10px; color: #44ee44; text-shadow: 0 0 5px #33ff33; } "
           ".input-field { background: black; border: 1px solid #33ff33; color: #33ff33; padding: 8px; width: 100%; margin-bottom: 10px; font-family: monospace; outline: none; border-radius: 4px; box-sizing: border-box; } "
           ".btn { background: none; border: 1px solid #33ff33; padding: 8px 16px; cursor: pointer; color: #33ff33; font-family: monospace; border-radius: 4px; } "
           ".error { color: #ff4444; margin-top: 6px; font-size: 0.9em; height: 1em; } "
           ".smiley { width: 64px; height: 64px; margin: 0 auto 10px auto; } "
           ".small { font-size: 0.8em; margin-top:4px; color:#aaa; }";
}

// Login JS
const char* get_login_js(void) {
    return "const form=document.getElementById(\"loginForm\");"
           "const errorDiv=document.getElementById(\"error\");"
           "form.addEventListener(\"submit\",async function(e){"
           "e.preventDefault();"
           "errorDiv.textContent=\"\";"
           "const formData=new FormData(form);"
           "const user=formData.get(\"user\");"
           "const pass=formData.get(\"pass\");"
           "try{"
           "const res=await fetch(\"/login\",{method:\"POST\",headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},body:\"user=\"+encodeURIComponent(user)+\"&pass=\"+encodeURIComponent(pass)});"
           "const text=await res.text();"
           "if(res.ok){"
           "window.location.href=\"/\";"
           "}else{"
           "errorDiv.textContent=text;"
           "}"
           "}catch(err){"
           "errorDiv.textContent=\"Error de conexión con el ESP32.\";"
           "}"
           "});";
}

// Terminal HTML
const char* get_terminal_html(void) {
    return "<!DOCTYPE html><html lang=\"es\"><head><meta charset=\"UTF-8\" /><title>ESP32 Retro Terminal</title>"
           "<link rel=\"stylesheet\" href=\"/terminal.css\"></head><body>"
           "<div class=\"logout\" onclick=\"doLogout()\">[LOGOUT]</div>"
           "<div id=\"term\"></div>"
           "<div class=\"input-container\">"
           "<span class=\"prompt\">&gt; </span>"
           "<input id=\"inputLine\" autocomplete=\"off\" autofocus />"
           "</div>"
           "<script src=\"/terminal.js\"></script></body></html>";
}

// Terminal CSS
const char* get_terminal_css(void) {
    return "body { background: black; color: #33ff33; font-family: monospace; margin:0; padding:0; display: flex; flex-direction: column; height:100vh; } "
           "#term { padding: 10px; white-space: pre-wrap; flex-grow:1; overflow-y:auto; } "
           ".input-container { display:flex; border-top:1px solid #33ff33; padding:5px; } "
           "#inputLine { width:100%; border:none; background:black; color:#33ff33; font-family:monospace; font-size:1em; outline:none; padding-left:5px; } "
           ".prompt { display:inline; white-space:nowrap; } "
           ".title { font-size:1.2em; font-weight:bold; color:#44ee44; text-shadow:0 0 5px #33ff33; } "
           ".logout {position: absolute;top: 10px;right: 15px;cursor: pointer;font-size: 1.1em;font-weight: bold;color: #ff5555;text-shadow: 0 0 3px #ff0000, 0 0 8px #ff0000;} "
           ".separator-line {border: 0;border-top: 1px solid #33ff33;margin: 10px 0;} ";
}

// Terminal JS
const char* get_terminal_js(void) {
    return "const term = document.getElementById(\"term\");"
           "const input = document.getElementById(\"inputLine\");"
           "let lastActivity = Date.now();"
           "const SESSION_LIMIT = 3 * 60 * 1000; "
           "const history = [];"
           "let historyIndex = -1;"
           "const commands = ["
           "  \"led r on\","
           "  \"led r off\","
           "  \"led b on\","
           "  \"led b off\","
           "  \"led all on\","
           "  \"led all off\","
           "  \"status\","
           "  \"help\","
           "  \"clear\""
           "];"
           "function showWelcome() {"
           "  term.innerHTML = \"\";"
           "  const title = \"<span class='title'>ESP32 RETRO TERMINAL</span><br>\";"
           "  const welcomeMsg = \"Bienvenido. Escribe 'help' para ver la lista de comandos.<br>\";"
           "  const separator = \"<hr class='separator-line'>\";"
           "  term.innerHTML = title + welcomeMsg + separator;"
           "}"
           "function appendLine(text) {"
           "  term.innerHTML += text.replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\") + \"<br>\";"
           "  term.scrollTop = term.scrollHeight;"
           "}"
           "function tryAutocomplete(current) {"
           "  if (!current) return null;"
           "  const matches = commands.filter(c => c.startsWith(current));"
           "  if (matches.length === 0) return null;"
           "  return matches[0];"
           "}"
           "function sendCommand(cmd) {"
           "  appendLine(\"> \" + cmd);"
           "  fetch(\"/cmd?c=\" + encodeURIComponent(cmd))"
           "    .then(resp => {"
           "      if (!resp.ok) {"
           "        throw new Error(\"Sesión expirada. Redirigiendo al login...\");"
           "      }"
           "      return resp.text();"
           "    })"
           "    .then(text => {"
           "      appendLine(text);"
           "      lastActivity = Date.now();"
           "    })"
           "    .catch(e => {"
           "      appendLine(\"[ERROR] \" + e.message);"
           "      setTimeout(() => { doLogout(); }, 1200);"
           "    });"
           "}"
           "input.addEventListener(\"keydown\", function(e) {"
           "  if (e.key === \"Enter\") {"
           "    const raw = input.value.trim();"
           "    if (raw.length === 0) return;"
           "    const cmd = raw.toLowerCase();"
           "    if (cmd === \"clear\") {"
           "      showWelcome();"
           "    } else {"
           "      sendCommand(cmd);"
           "      history.unshift(cmd);"
           "      historyIndex = -1;"
           "    }"
           "    input.value = \"\";"
           "    lastActivity = Date.now();"
           "    e.preventDefault();"
           "  } else if (e.key === \"ArrowUp\") {"
           "    if (history.length === 0) return;"
           "    if (historyIndex + 1 < history.length) historyIndex++;"
           "    input.value = history[historyIndex];"
           "    e.preventDefault();"
           "  } else if (e.key === \"ArrowDown\") {"
           "    if (historyIndex > 0) {"
           "      historyIndex--;"
           "      input.value = history[historyIndex];"
           "    } else {"
           "      historyIndex = -1;"
           "      input.value = \"\";"
           "    }"
           "    e.preventDefault();"
           "  } else if (e.key === \"Tab\") {"
           "    e.preventDefault();"
           "    const current = input.value.trim().toLowerCase();"
           "    const auto = tryAutocomplete(current);"
           "    if (auto) {"
           "      input.value = auto + \" \";"
           "    }"
           "  }"
           "});"
           "setInterval(() => {"
           "  if (Date.now() - lastActivity > SESSION_LIMIT) {"
           "    appendLine(\"[INFO] Sesión expirada por inactividad. Cerrando...\");"
           "    setTimeout(() => { doLogout(); }, 800);"
           "  }"
           "}, 2000);"
           "showWelcome();"
           "function doLogout() {"
           "  fetch(\"/logout\").then(() => { window.location.href = \"/\"; });"
           "}";
}

